### ISSUE TITLE
REPL Commands - Better usage experience

### ISSUE THREAD

**Issue by paulbouwer** [scriptcs/scriptcs#1088]
When using the REPL Commands to explore the upcoming `openide` command, I noticed that the usage of the commands was not always clear. Also the usage checking was not consistent.

```
> :alias
You must specifiy the command name and alias, e.g. :alias "clear" "cls"
> :cd

System.NullReferenceException: Object reference not set to an instance of an object.
   at ScriptCs.ReplCommands.CdCommand.Execute(IRepl repl, Object[] args) in c:\Build\scriptcs\src\ScriptCs.Core\ReplCommands\CdCommand.cs:line 27
   at ScriptCs.Repl.Execute(String script, String[] scriptArgs) in c:\Build\scriptcs\src\ScriptCs.Core\Repl.cs:line 79

> :openide

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ScriptCs.ReplCommands.OpenIdeCommand.Execute(IRepl repl, Object[] args) in c:\Build\scriptcs\src\ScriptCs.Core\ReplCommands\OpenIdeCommand.cs:line 22
   at ScriptCs.Repl.Execute(String script, String[] scriptArgs) in c:\Build\scriptcs\src\ScriptCs.Core\Repl.cs:line 79

>
```

I'm suggesting an update to  `IReplCommand` as follows:
<pre>
namespace ScriptCs.Contracts
{
    public interface IReplCommand
    {
        string CommandName { get; }
        string Description { get; }
        <b>string Usage { get; }</b>
        <b>bool IsValidUsage(IRepl repl, object[] args)</b>
        
        object Execute(IRepl repl, object[] args);
    }
}
</pre>

Then `ScriptCs.Repl` could call `IsValidUsage` before calling `Execute`. If `IsValidUsage` returns `false`, then `Usage` could be called to print out usage details. Any exception should still print the usage message, with the exception logged to the debug output. This flow would enforce a user experience consistency across the commands.

Adding the `Usage` method also has an additional benefit of being able to get usage information for a command from the `:help` command.

```
scriptcs (ctrl-c to exit or :help for help)

> :help

Use :help <command> to get help for a specific command

The following commands are available in the REPL:
:alias          Alias a command with a custom name.
:cd             Changes the working directory to the path provided.
:clear          Clears the console window.
:cls            Clears the console window.
:cwd            Displays the current working directory.
:exit           Exits the REPL.
:help           Shows this help.
:install        Installs a Nuget package.
:openide        Opens a script in the default IDE associated with sln files.
:references     Displays a list of assemblies referenced from the REPL context.
:reset          Resets the REPL state. All local variables and member definitions are cleared.
:scriptpacks    Displays information about script packs available in the REPL session.
:usings         Displays a list of namespaces imported into REPL context.
:vars           Displays a list of variables defined within the REPL, along with their types and values.
```

```
> :help alias

alias                                   <- IReplCommand.CommandName
  Alias a command with a custom name.   <- IReplCommand.Description

usage:                                  <- IReplCommand.Usage
  :alias "<command>" "<alias>"

options:
  <command>  The command to alias. 
  <alias>    The alias.

examples:
  :alias "clear" "cls"
```

The `:help` command should also be written to produce the usage of the original command for any alias invoked with the help command.

**Comment by glennblock** [comment]
I'd go one step further and provide a flag that says whether arbitrary
expressions are supported. For example :openide blows if you pass test.csx
not quoted as it tries to evaluate it. This is pretty lame imo. I would be
fine with saying expressions don't work with openide and the params are
just taken as literals.

**Comment by glennblock** [comment]
I like the suggestion though!

**Comment by adamralph** [comment]
One thing to bear in mind is that the evaluation of REPL command arguments is general across all commands and is performed at a lower level than the command implementation itself. Things could get messy if some commands have their arguments evaluated and others don't. It would be necessary to remember to quote strings on some commands and not quote them for others and I think that's a rather nasty UX. However, I agree that having to wrap string arguments in quotes is ugly but it's the price to pay for having arguments that can be evaluated.

**Comment by adamralph** [comment]
Big :+1: to the feature proposal, btw.

**Comment by adamralph** [comment]
A comment on the proposal: it seems strange to mix in the `options:` and `examples:` info and layout all into the `Usage` property. For one thing, it's assuming knowledge of the formatting that is being used to display the rest of the command help by introducing it's own line breaks, colons and indents, but this won't hold in the general case. The commands themselves live in side core and the some other REPL host may display them in it's own way which could be completely different. It would seem more natural to also introduce `Options` and `Examples` properties and pass them through the same rendering as the other properties.

**Comment by paulbouwer** [comment]
That also didn't sit too well with me while I was formatting the output of `:help alias` in the issue. Didn't want to make it overly complex but I do like all the detail in the usage. 

I think adding an `Options` and `Examples` property would be better.
