### ISSUE TITLE
Interactive mode crashes when Process.Start is used

### ISSUE THREAD

**Issue by jamesqo** [scriptcs/scriptcs#1121]
Hey! I just installed scriptcs and it's been a pretty awesome experience so far. The install process was super smooth and I **love** the interactive mode.

For some reason, when I'm trying to run Process.Start in interactive I keep getting a `JsonSerializationException`. Here's the full output from my terminal:

``` csharp
> using System.Diagnostics;
> Process.Start(@"C:\Windows\System32\notepad.exe");

Newtonsoft.Json.JsonSerializationException: Error getting value from 'ExitCode' on 'System.Diagnostics.Process'. ---> System.InvalidOperationException: Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at GetExitCode(Object )
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at ScriptCs.Hosting.ObjectSerializer.Serialize(Object value)
   at ScriptCs.Repl.Execute(String script, String[] scriptArgs)
```

Notepad still appears to start successfully, though, so I'm not quite sure why an exception is getting thrown. Even weirder, when I type my next command Notepad starts again:

``` csharp
* Console.WriteLine("Hello world!");
Hello world!
[a new Notepad window pops up]
> 
```

Anyway, just thought you might want to look into that. You guys have a pretty cool project, keep up the good work!

**Comment by adamralph** [comment]
@jamesqo thanks for raising this.

The reason this happens is that the result of the call to `Process.Start()` is a `Process` object and when scriptcs tries to serialise it (via JSON.NET) for output to the REPL, the `Process.ExitCode` property throws an exception. It's utterly horrible API design on the part of `Process`, but there you go.

We should probably just catch the serialization exception and wrap it in a friendlier exception.
