### ISSUE TITLE
Loading System.Management from GAC fails.

### ISSUE THREAD

**Issue by Hammerstad** [scriptcs/scriptcs#1151]
Hello.

We've been using scriptcs as a buildsystem/glue, and it has been working great until the release of version 0.16.0.

We now get the following error when running:

    ERROR: Error executing script 'build.csx' [FileNotFoundException] Assembly not found.

Narrowing it down to the following:

    #r "System.Management.dll"

A file (`build.csx`) containing only `#r "System.Management.dll"` creates this behaviour when executed (`scriptcs build.csx`).

Running `gacutils.exe -l` shows us that System.Management is in the GAC:

    System.Management, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL

Is there anything in the new release that changes the expected behaviour of `#r`?

**Comment by khellang** [comment]
@Hammerstad We've swapped out the Roslyn engine, which is ultimately what builds and executes the scripts. This is probably why.

Could you run it with logging level set to debug and paste the output? Also, is there any difference if you change `System.Management.dll` to just `System.Management`?

**Comment by andmos** [comment]
@khellang yeah, we have build our own buildsystem based on ScriptCS. Works like a charm!

**Comment by Hammerstad** [comment]
> @Hammerstad Cool!  For DIPS?

That's correct. Most of our new stuff uses scriptcs as a glue between code, doc, buildserver and chocolatey/nuget.

> Could you run it with logging level set to debug and paste the output? Also, is there any difference if you change System.Management.dll to just System.Management?

I decided to try the renaming first, which fixed our issue. Just in case the debug logs give you anything, I'll post them as well:

```
C:\Users\emh\cygwin64\home\emh\git\Project\build>scriptcs build.csx -D
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IAppDomainAssemblyResolver
DEBUG: [ScriptCs.Hosting.InitializationServices] Registering initialization services
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFileSystem
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAssemblyUtility
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageContainer
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IInstallationProvider
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageInstaller
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Hosting.IModuleLoader
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAppDomainAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFilePreProcessor
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Autofac to version:3.3.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Autofac.Integration.Mef to version:3.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Common.Logging to version:2.1.2.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ICSharpCode.NRefactory.CSharp to version:5.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ICSharpCode.NRefactory to version:5.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Microsoft.CodeAnalysis.CSharp to version:1.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Microsoft.CodeAnalysis.Desktop to version:1.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Microsoft.CodeAnalysis to version:1.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Microsoft.CodeAnalysis.Scripting.CSharp to version:1.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Microsoft.CodeAnalysis.Scripting to version:1.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Microsoft.Web.XmlTransform to version:2.1.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Mono.Cecil to version:0.9.5.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Mono.CSharp to version:4.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Newtonsoft.Json to version:6.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly NuGet.Core to version:2.8.60717.93
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly PowerArgs to version:2.0.4.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Contracts to version:0.16.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Core to version:0.16.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Engine.Common to version:0.16.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Engine.Mono to version:0.16.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Engine.Roslyn to version:0.16.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Hosting to version:0.16.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly System.Collections.Immutable to version:1.1.33.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly System.Reflection.Metadata to version:1.0.18.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly scriptcs to version:0.16.0.0
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IModuleLoader
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IFileSystem
DEBUG: [ScriptCs.Hosting.ModuleLoader] Only CSharp module is needed - will skip module lookup
DEBUG: [ScriptCs.Hosting.ModuleLoader] Initializing module: System.Reflection.RuntimeAssembly
DEBUG: [ScriptCs.Hosting.ScriptServicesBuilder] Resolving ScriptServices
DEBUG: [ScriptCs.Hosting.ScriptServicesBuilder] Registering runtime services
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFileSystem
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAssemblyUtility
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageContainer
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IScriptHostFactory
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFilePreProcessor
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IScriptPackResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IInstallationProvider
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageInstaller
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.ScriptServices
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IObjectSerializer
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IConsole
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFileSystemMigrator
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IScriptLibraryComposer
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IVisualStudioSolutionWriter
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IAssemblyResolver
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IInstallationProvider
DEBUG: [ScriptCs.ScriptExecutor] Initializing script packs
DEBUG: [ScriptCs.FilePreProcessor] Starting pre-processing
DEBUG: [ScriptCs.FilePreProcessor] Processing build.csx...
DEBUG: [ScriptCs.FilePreProcessor] Pre-processing finished successfully
DEBUG: [ScriptCs.ScriptExecutor] Starting execution in engine
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Starting to create execution components
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Creating script host
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Creating session
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to System
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to System.Core
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to System.Data
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to System.Data.DataSetExtensions
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to System.Xml
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to System.Xml.Linq
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to System.Net.Http
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to Microsoft.CSharp
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to C:\ProgramData\chocolatey\lib\ScriptCs\tools\ScriptCs.Core.dll
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to C:\ProgramData\chocolatey\lib\ScriptCs\tools\ScriptCs.Contracts.dll
DEBUG: [ScriptCs.Engine.Common.CommonScriptEngine] Adding reference to System.Management.dll
ERROR: [ScriptCs.Command.ExecuteScriptCommand] Error executing script 'build.csx' [System.IO.FileNotFoundException] Assembly not found.
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.ResolveReference(String assemblyDisplayNameOrPath)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableExtensions.GetCount[T](IEnumerable`1& sequence)
   at System.Collections.Immutable.ImmutableArray`1.InsertRange(Int32 index, IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.AddReferences(IEnumerable`1 references)
   at ScriptCs.Engine.Common.CommonScriptEngine.Execute(String code, String[] scriptArgs, AssemblyReferences references, IEnumerable`1 namespaces, ScriptPackSession scriptPackSession)
```

Thanks a lot for the help :smile:

**Comment by khellang** [comment]
> That's correct. Most of our new stuff uses scriptcs as a glue between code, doc, buildserver and chocolatey/nuget.

That's really cool to hear :grin: Please keep the feedback coming :smile:

> I decided to try the renaming first, which fixed our issue.

Yeah, I think they might've changed the algorithm for looking up references between the old (remember, it was a CTP from 2012 :stuck_out_tongue_closed_eyes:) and the new version. If you add the `.dll` extension, it'll try to look for a local file. This is the closest issue I could find about the issue: https://github.com/dotnet/roslyn/issues/6742

**Comment by Hammerstad** [comment]
> That's really cool to hear  Please keep the feedback coming

Will do :smile:. We introduced scriptcs last summer, and it has gradually spread throughout the organization. Quite happy with the experience so far :smile: 

> Yeah, I think they might've changed the algorithm for looking up references between the old (remember, it was a CTP from 2012 ) and the new version. If you add the .dll extension, it'll try to look for a local file. This is the closest issue I could find about the issue: dotnet/roslyn#6742

Yeah, it's been a couple of years, suppose lots have happened since then.

The fix seems to be backwards-compatible (at least with 0.15.0). Long story short, things are back to normal :smiley: 

Again, thanks for the quick response and helpful feedback :smiley: 
Suppose this can be closed.
