### ISSUE TITLE
Installing Newtonsoft.Json on OSX via scriptcs fails.

### ISSUE THREAD

**Issue by jolson88** [scriptcs/scriptcs#1171]
I tried installing Newtsonsoft.Json via scriptcs with the following command:
`scriptcs -install Newtonsoft.Json`

It fails with the following error:
`ERROR: Error installing package. [InvalidOperationException] 'Microsoft.CSharp' already has a dependency defined for 'System.Dynamic.Runtime'.
ERROR: Package installation failed. [AggregateException] One or more errors occurred.`

Environment:
- I'm running on OSX (El Capitan, 10.11.4)
- Fresh install of scriptcs via Homebrew

**Comment by glennblock** [comment]
Thanks for reporting this. I will look into it.

**Comment by glennblock** [comment]
Can repro on Windows as well.

**Comment by glennblock** [comment]
Looks like this is occurring from the NuGet.Core. Stack trace below....

```
   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.LocalPackageRepository.OpenPackage(String path)
   at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
   at NuGet.LocalPackageRepository.<>c__DisplayClass13.<FindPackage>b__f(String path)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NuGet.LocalPackageRepository.FindPackage(Func`2 openPackage, String packageId, SemanticVersion version)
```

**Comment by glennblock** [comment]
Looks like this is an issue with the latest JSON.NET package. If you use 

```
-install newtonsoft.json -p 8.0.3
```

It will work.

**Comment by glennblock** [comment]
@david-driscoll. This is similar to your issue. Based on my debugging, it looks like it is something in Nuget.Core.

**Comment by glennblock** [comment]
Progress thanks to the Nuget team!

https://github.com/NuGet/Home/issues/3252

**Comment by glennblock** [comment]
Ok, I've verified with the latest Nuget.Core 2.12.0 (thanks Nuget team for releasing it) that the error goes away. I will see about getting a patch with the latest Nuget version

**Comment by enzian** [comment]
#1176

**Comment by enzian** [comment]
This looks like the same issue as #1176

**Comment by glennblock** [comment]
Should be fixed.
