### ISSUE TITLE
Need a meaningful error when a module that is specified is not found

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#786]
Currently specifying a module that is not found yields the following extremely unhelpful error :-)

```bash
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ScriptCs.Hosting.ScriptServicesBuilder.Build() in c:\src\scriptcs\src\ScriptCs.Hosting\ScriptServicesBuilder.cs:line 39
   at ScriptCs.Command.CommandFactory.CreateCommand(ScriptCsArgs args, String[] scriptArgs) in c:\src\scriptcs\src\ScriptCs\Command\CommandFactory.cs:line 61
   at ScriptCs.Program.Main(String[] args) in c:\src\scriptcs\src\ScriptCs\Program.cs:line 19
```

**Comment by adamralph** [comment]
I think this behaviour may have changed in the latest dev version and this issue may now be superseded by https://github.com/scriptcs/scriptcs/issues/891 - I'll do some tests and confirm.

**Comment by adamralph** [comment]
Superseded by #891.

**Comment by fir3pho3nixx** [comment]
Guys, has this error come back in some way?

If you clone https://github.com/cryosharp/deploycs

    cd ./scripts/
    scriptcs -install
    scriptcs deploycs

It gives the error

    ERROR: Script execution failed. [System.Collections.Generic.KeyNotFoundException] The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ScriptCs.ScriptPackManager.Get[TContext]()
   at Submission#0.<Factory>(Session session)

I first used the release and then switched to nightly build. Still the same issue.

**Comment by adamralph** [comment]
@fir3pho3nixx it hasn't been fixed yet. The work is happening over at https://github.com/scriptcs/scriptcs/issues/891

**Comment by fir3pho3nixx** [comment]
Thanks, checked this over and the fixes seem to be going into the
ModuleLoader. Will debug and send pull request if I can.
